### ISSUE TITLE
Time Spent does not always update

### ISSUE THREAD

**Issue by DamianSuess** [abstractspoon/ToDoList_Core#1]
**Version**: 7.1.RC1
**OS**: Win10
**User level**: Administrator
**View:** Task Tree
**Frequency:** Once weekly
**Issue:**
When tracking time, the application will sometimes not track time whether it is manually inputted on a task or clicking, Start/Stop Tracking.

I did create a detailed recorded bug report, with notes each step of the way. Where should i email it to, since i'm not seeing an attach button on GitHub's issue system.

**Workaround:**
Close ToDoList and restart application.

**Comment by abstractspoon** [comment]
Please post all issues to our [Google Group](https://groups.google.com/forum/#!categories/abstractspoon-todolist-support) pls.
